server:
  port: 8001

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_client
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
      instance:
        hostname: localhost

resilience4j.circuitbreaker:
  instances:
    clientCB:
      #registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
resilience4j.timelimiter:
  instances:
    clientCB:
      timeoutDuration: 2s
      cancelRunningFuture: true

resilience4j.bulkhead:
  instances:
    clientCB:
      maxWaitDuration: 10ms
      maxConcurrentCalls: 20
