server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: client-service
        uri: lb://client-service
        predicates:
        - Path=/api/client/**
      - id: product-service
        uri: lb://product-service
        predicates:
        - Path=/api/account/**
        - Path=/api/accountBussinesPerson/**
        - Path=/api/accountNaturalPerson/**
        - Path=/api/creditBussinesPerson/**
        - Path=/api/creditNaturalPerson/**
        - Path=/api/virtualCoin/**
